version: '3.7'

services:
  nginx:
    build:
      context: .
    volumes:
      - ./conf:/usr/local/nginx/conf
    logging:
      driver: json-file
    healthcheck:
      test: ["CMD", "/bin/bash", "-c", "/usr/bin/curl --silent -f http://127.0.0.1:80 > /dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443

